apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBtGwDPsjzCzQX6IHZgfhb43f7lCsXTvTikexG6ANR5NHXdhAzEFuIYDk3SvUPQNlEx6ozzuERguAJ+KeHItAZIwfQ+SOtHtycqmIjZcbNDWanSyES993PYQ25Z7MTuGyTIx4zgMi8s02WlyQpJFzpkhVm6t7eB88GrRklr/b0LlI+d7tnolXbY6sjkxByIogfhgwQoIySo7wjeYEpbdwNMkJtTK4vWE+npURRNRlfJ4ZQWostS1tJdKuhXmJAIIxxRBomBAKV/akOVjg4B/N3gg7q7Q9l/xBLaShHHMasNfuQN2lnBe91vrS6e9/4jnchlK/78ea0GYtQcjBj66cFYIEuEKL/C6abW3vpW4ujwWGuu1vvIqCKDi7mc67cKpXEjFW9WebM6q922KVkU54OUgHj6xra0RhzGoOEq5OW9UmPg0gKOaISc7KWp7he4WfaypJvnFsi6PrVVEvzD7YuYjmvKFeOzBOBAvKtfv7tqmq8jAkCvl7Y+JCUPsVMr5Wp1I5qtOY9gO2NktInpnL0AZifcuqIUJYU4eFaSx/Jgh8ETzkEKHv+D675uzVaH7xytEyo16jR88oUlzy7e9w38+jO07Nhz55/wuCqLOphhv8mZatF+wreL3elwnbnnjv8QBEUqiHypiNjR//s7HKxkHdZzXYjRCn5ibiCvQiWHEft7hjveL07KH6MEn2+KmqP+OHeb9iKFaNAnq7eGJ52qV9uPKgM/M5ZyzKcbd+24gQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: redis
    type: Opaque
