apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    access_key: AgCPG2zbDoC6LjX98CZmGJJF2FIUBZaZmRYMy4DGwSyswzCPzYNEw+9V40UlQ+yn+JWUVrP/f3Hw5BgUY1m4rV7VRsgMzbQ1Sf+2o8zuozYXj50BeCwb2imAnCRZMxXrTWRJs2xwWG/LnlECBrlv1XElC64X2iUTRLD+8omQznaQHXR+zzutIT+qKB92BhBc9sD0PybYxI737hyq4LEvzH+tdglAsnoRT6b30hMa9TiQEiyZFDZAmmeCZGjjTph/jrcsEki96pi3mTvzsoiRA8mjTXELIHRRSIdrGvEC0RAFYJzWMF2FuKlJXCGHeM2WrWVdmjg59g2yaQn2WEulm0D6rEwnvECC90l6Mk5HtJS9iJ1cZggASKcQfUbDFQ3foMevux9uQpviv9uwmB8hcIpxSgzj1KTx7wMmP7PCWM0op/HzH4WaDuaJ/6BtYWn7NsJh4f3Tmpa40PrmWZewWrjglK7Ia+YfzdSqtYzptNLSrqUB/q/q4ynGIxkK/F38ZqDmzorYHxAALlEbUXfwhgynwh9jmoX2ogaTrbBXFUc3tc5z8NXm00SOsOWdXVKxuEfTKKst3LCK2EwZ///W+2lSBLdUS7SQTMiWZLHQQcrh9ig8DCiIxrf9XHvtm7NOXaDwqiTF8YlHVKBIR+wDTnU4IVOAaWhwFQCikzEeUFvtVeRuh4ZQ60t5H7qE5l3sBB5fPqlrw+KNAHFE0+QFikxrk4+2wbObnydKaqIUGhJwKWYr2839c/5m
    key_id: AgAaLdr3OEXVafyQVnDE2aDRtQFGUnZJjTw8VZlBXJ2Bh1zCVImg2uroxmdQiEWFOluv7Kx7VqoEZXLyqMTbmwqi0w4UPK2LMGlDFvDgqb2gUW7Bd8O6mP7UNo9IgZWDoN02CtivtAr0YSQPXiqCJ5gP0UVAwjINbE50LbTbRdvK9Qx5UP/exqjAHoQY949wTawGCDehwa3tuX483o/qsNfLLY0j0vsJYWaPiSf6ef8/al5z4gr1R4Zr3khrrXTJ7KbSoRzRKU39d0f20bzlr6VLgNEnUM/RLKKblUktMhofSswxryfZOuaVw6+OMFe9CeWf5RC1h2QXt15582w/tQma4voF8P7NDVZVraagSRZStqrLNRdvA+DVoWiISrZgcI1z687GdsxE147sEGKm2CNnE4f1V/hxtiUGc+jzboqafwTjXnI9Z0QldbXWkOltINK2acmJW/MHN4ii+zkayTGDgpppo357Gvz6OLh1PY2X7Rm0r1wpsp6leQQdXUs03HzsWUCB+hpyvA5/IlxHNplc0iCDdANZYNJQYbO4/HSd6re3gHLDkW59TNRaiQK2oCL3hc7j2ODj1zoV6Tfuczk2JWjDsX+HRr0+XDyb8/A8nZopbDjlhj8ObPQLsb2Mo4AvEu08YsaC6EIGLhymXZPh2eqJbYMi6vavUFUzbPQWtFryIVQyVgr1YaIUpQVd2TO2te8vxD/r15xL1nRW7ZuaIxHC1g==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system
    type: Opaque
