apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-secret
  namespace: postgres
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgABZlPrQ/Izs/PxgV60bs6i80KCwQ4Ugz+df1IYyf7xTerKNj3++BVZpUCM0HtqgRLubGkj+92n3m2v6cV8y3yeQmF99nikp+Zn0KWXZG5Wbhik/BstChl7peai4M6J+8PVujCTTqztguhomD7+BA+9C3q2MYtrv7j6hDTG+8ZsJT6Za468obPiyRQdgvGdZJiTuJDHE6wfFDcF5azebLC4ae4rauBVTwwnJi/XrTpwjAaYsPxmbmHZZ9KHys094uxxOVO+/ZHnaqayUHXrVNQP9CtlM7sA+BXAS8pYp2NrCZ6r60YkwZFhrF8Px45Kr191kwjJz7atC/LEpNBUK3Nx95aMT7fzq1v+6tdo17MfOZT72fajyhZVABVRliDPPan9tDSu8gvl/dOVF4dqnawTR3BIPIiFVt7Zr14nmGxHGbgiO8hZemNKm2zPXSFmvM44W9vNFL3ImF/UNQ/pMUfpoiaTqTjaKNKnWmAfTSDu6UWcLjloBenaGdFZGeS23PA28/KePsBb/aVAudtO8Hmsx6b5cjOJZgQ7HZZyp6BQgB7gOTKGloxgGJ9wQqkV5JPctmrpbEyeEz0XAKCUoJSMaM8pHjpWVkR+ajurEliZ1qGpluHfH2bwj+tPZ+Lfyshj71xP57zraKCgK4DGYNbqOXSvFCike78+uT5KldijAR/DPUROKA55Eh4ByuhpGvpfOMme3PbUdLFdnISFlDlpf1UV4A==
    PGADMIN_DEFAULT_PASSWORD: AgAU3uGnlWQcvhggbrhDkpyvI84ZN51xSqusBFiE9+sNoFGSO03FBiIs54v7CmlXa3XcgaTjEDVxDJ4d9DUrEbrqE3IGfzOxZTlN8jiQ9TvmuXNAb4z3uWsyKHp3Vy7Py5qgr2MZishSLftUcJWZbjHNvbzgdb2dbhe82XFZcMfvvaJLdsidxn0/WIeIGSbtXxm0DA7LYnlfs6mLzzAUhamooWLPY3Fn5Br9LBec1/a2IL2wJCXnvv9gMSjlDMJqwy1CJ8LzH/LZgVNLOGf+fHzodzOU97kBflOw6SIaa8OToArFGnSCVV4rAQeBZOy8WQvx2oOsG1ojy+wvT6lFsgWXD8+1hgCCOVo1HRbCgoVnNCU74rsWo+0vUdHmV/XtNCb2IQYzxiU+6r3bpAwpQ46Ly+Ai+IcWGhLW3RSZH0uYq8ijo7YFNWILfLW0AzkDiQoebX4k20Wfid3xZFZXaLnK6F7BcXNCol7A3/Q98k2+XMRa6A+pZCfHLYk6YMdbQRqObrNvUPEQ27mk4vpOGXjwdw/ForE2GO1Yks+RF1u0zZynm0NImIdLY1/9ZwiiopfpdmXq1uQeMT2j2bUm3bdi5DeiIQUy46NAqfgfMaZyM+LwzECrZOcrsRp6U50XGXqaJa//XnfhRMZtYTbmMdpZNhYgHx5mn0KFPLuK50q54EqaYpqlxde4MbeL+johbx7nyNOnYYeRIcCuWHML0q7KRtdXaYU9r53rjs1X6NQp2w==
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-secret
      namespace: postgres
    type: Opaque
