apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgpool-secret
  namespace: postgres
spec:
  encryptedData:
    admin-password: AgBx7yx1g8SsPiJah0TSHv3n2Y91gtGva1m3I/x4LzxWaTrNeL5lb1ToZpi2vNde2HkBNkdqovKKe+N54bAWL05lOeY4WWJ5gFcSjWsUrKpZggB1H+EusOAjIXafqW4+fumyS3KSrKB4AbEHTxDrd7Z+MVk0gxnbr6JZ1ZkdkTFs7j1P5n+hZW+97kCA7jQXFRaQM+bMC69x030fJwkSNQJnE/R6eh0q7BZpzHh2pDnHpMRmY4az84wE1nz3/e4KILZevEkCN1X1u45nzXloDFc1hpPkOE9sRdmsS/Jem9c1m5TjTVgbt/H02wyHo5epNatRVQfjJsvdlxVfo1quvMRkPn6XxLX8UaDJAu7sFsc3kZjj4L5RyTsbi/gwXbzHfmOXku9dWwXxaGaQv0B+0UU4r3lu7cTfufGtyxzIZ9Pqs/KhSsjnNGkOYl1taS4jonjjg439RVEudOI8gqPcIUIr2m4FT162sOp9bNe+OyAToQDw7BtVj9WsbiIXBnQEzcGRTDcZlEYH/NyQvnGEQ6t7PcS/OPpkGlRhsHaUUmMElETGKw/VSox6RXKxE9uEphQrTXPU/gYWz2qK7pmgqeCf0+2KXryEkNAgTn7Z1Dj1g9Cuj0jm7XugIDe3MU0ntHfcGti3/BkTlKCNYEFtN0q8SGC0LF+e1DoCJHl7FDjY8BZzeBel8JcHgq9YFutP5RoaSlxdZBz9rV1iQSiyAQUGhA5ou4HWyMuam87baAADUA==
  template:
    metadata:
      creationTimestamp: null
      name: pgpool-secret
      namespace: postgres
    type: Opaque
